flags:
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.11.2.1
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.13.0.2
- base-compat-0.9.1
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- byteable-0.1.1
- bytestring-conversion-0.3.1
- case-insensitive-1.2.0.7
- cereal-0.5.3.0
- comonad-5
- connection-0.2.5
- contravariant-1.4
- cookie-0.4.2.1
- cryptonite-0.17
- data-default-class-0.1.2.0
- distributive-0.5.0.2
- dlist-0.8.0.1
- double-conversion-2.0.1.0
- exceptions-0.8.3
- fail-4.9.0.0
- free-4.12.4
- hashable-1.2.4.0
- hourglass-0.2.10
- http-api-data-0.2.4
- http-client-0.5.1
- http-client-tls-0.3.0
- http-media-0.6.4
- http-types-0.9.1
- kan-extensions-5.0.1
- lens-4.14
- memory-0.13
- mime-types-0.1.0.7
- mmorph-1.0.6
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- parallel-3.2.1.0
- parsec-3.1.11
- pem-0.2.2
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- safe-0.3.9
- scientific-0.3.4.9
- semigroupoids-5.1
- semigroups-0.18.2
- servant-0.8
- servant-client-0.8
- socks-0.5.5
- stm-2.4.4.1
- streaming-commons-0.1.15.5
- string-conversions-0.4
- syb-0.6
- tagged-0.8.5
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- tls-1.3.8
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.1
- utf8-string-1.0.1.1
- vault-0.3.0.6
- vector-0.11.0.0
- void-0.7.1
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- zlib-0.6.1.1
resolver: ghc-7.10.3
